name: 2025-08-29-pycongr2025-tutorial-thinking-in-arrays
channels:
  - conda-forge
dependencies:
  - python>=3.12.11,<3.14
  - aiohttp>=3.12.14,<4
  - awkward>=2.8.5,<3
  - fsspec>=2025.7.0,<2026
  - hist>=2.8.1,<3
  - jupyterlab>=4.4.5,<5
  - jupyterlab-deck>=0.2.0,<0.3
  - jupyterlab-mathjax3>=4.3.0,<5
  - matplotlib>=3.10.3,<4
  - mplhep>=0.4.0,<0.5
  - numba>=0.61.2,<0.62
  - numexpr>=2.10.2,<3
  - numpy>=2.2.6,<3
  - pandas>=2.3.1,<3
  - pyarrow>=20.0.0,<21
  - requests>=2.32.4,<3
  - scikit-learn>=1.7.0,<2
  - scipy>=1.16.0,<2
  - pip
  - pip:
      - jax>=0.4.38,<0.7
